/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.Agencias; 
import DAO.Clientes;
import DAO.ConnectDAO;
import java.util.Set;
/**
 *
 * @author Alunos
 */
public class Agências extends javax.swing.JFrame {
    String operacaoAtivaGlobal = "Nenhum";
    /**
     * Creates new form Agências
     */
    public Agências() {
        initComponents();
    }
    public Agências (String operacaoAtiva) {
        
        initComponents ();
        operacaoAtivaGlobal = operacaoAtiva;
        String operacao = "Incluir" ;
        
        if (operacaoAtiva.equals(operacao)) {
          jButton1.setText("Incluir BD");
          jButton2.setVisible(false);
          jButton3.setVisible(false);
          
          jLabel1.setVisible(true);
          jLabel2.setVisible(true);
          jLabel3.setVisible(true);
          jLabel4.setVisible(true);
          jLabel5.setVisible(true);
          jLabel6.setVisible(true);
          jLabel7.setVisible(true);
          jLabel8.setVisible(true);
          jLabel11.setVisible (true);
          jTextField1.setVisible(true);
          jTextField2.setVisible(true);
          jTextField3.setVisible(true);
          jTextField4.setVisible(true);
          jTextField5.setVisible(true);
          jTextField6.setVisible(true);
          jTextField7.setVisible(true);
          jTextField8.setVisible(true);
          jTextField9.setVisible(true);
          jTextField10.setVisible(true);
        }
        
        operacao = "Alterar";
        if (operacaoAtiva.equals(operacao)){
          jLabel2.setVisible(false);
          jLabel3.setVisible(false);
          jLabel4.setVisible(false);
          jLabel5.setVisible(false);
          jLabel6.setVisible(false);
          jLabel7.setVisible(false);
          jLabel8.setVisible(false);
          jTextField1.setVisible(true);
          jTextField2.setVisible(false);
          jTextField3.setVisible(false);
          jTextField4.setVisible(false);
          jTextField5.setVisible(false);
          jTextField6.setVisible(false);
          jTextField7.setVisible(false);
          jLabel10.setVisible(false);
          jLabel9.setVisible(false);
          jLabel11.setVisible(false);
          jTextField8.setVisible(false);
          jTextField9.setVisible(false);
          jTextField10.setVisible(false);
          
          jButton1.setText("Pesquisar");
          jButton2.setVisible(false);
          jButton3.setVisible(false);
        }
        
        operacao = "Excluir";
        if (operacaoAtiva.equals(operacao)){
          jLabel2.setVisible(false);
          jLabel3.setVisible(false);
          jLabel4.setVisible(false);
          jLabel5.setVisible(false);
          jLabel6.setVisible(false);
          jLabel7.setVisible(false);
          jLabel8.setVisible(false);
          jTextField1.setVisible(true);
          jTextField2.setVisible(false);
          jTextField3.setVisible(false);
          jTextField4.setVisible(false);
          jTextField5.setVisible(false);
          jTextField6.setVisible(false);
          jTextField7.setVisible(false);
          jLabel10.setVisible(false);
          jLabel9.setVisible(false);
          jLabel11.setVisible(false);
          jTextField8.setVisible(false);
          jTextField9.setVisible(false);
          jTextField10.setVisible(false);
          
          jButton1.setText("Pesquisar-Excluir");
          jButton2.setVisible(false);
          jButton3.setVisible(false);
        }
    }
    
    Agencias agencia_tela = new Agencias();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id_Agencia:");

        jLabel2.setText("Nome Agência:");

        jLabel3.setText("Endereço:");

        jLabel4.setText("Número:");

        jLabel5.setText("Complemento:");

        jLabel6.setText("Bairro:");

        jLabel7.setText("Cep:");

        jLabel8.setText("Fone:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpar tela");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setText("Agências");

        jLabel11.setText("Cidade:");

        jLabel9.setText("UF:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(7, 7, 7)
                                .addComponent(jTextField4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jButton1)
                                .addGap(28, 28, 28)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(14, 14, 14)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(57, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        if (operacaoAtivaGlobal.equals(operacao))
        {
        agencia_tela.setNumAgencia(jTextField1.getText());
        agencia_tela.setNome(jTextField2.getText());
        agencia_tela.setEndereco(jTextField3.getText());
        agencia_tela.setNumero(jTextField4.getText());
        agencia_tela.setComplemento(jTextField5.getText());
        agencia_tela.setBairro(jTextField6.getText());
        agencia_tela.setCep(jTextField7.getText());
        agencia_tela.setFone(jTextField8.getText());
        agencia_tela.setUF(jTextField9.getText());
        agencia_tela.setCidade(jTextField10.getText());
        
        ConnectDAO objcon = new ConnectDAO();
            objcon.connectDB();
            objcon.insereRegistroJFBD("AGENCIAS", agencia_tela.dadosSQLValues());
            
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        }
        
        operacao = "Alteração";
        if (operacaoAtivaGlobal.equals(operacao)){
            
            ConnectDAO objcon = new ConnectDAO();
            
            Agencias agencia_tela = new Agencias();
            agencia_tela.setNumAgencia(jTextField1.getText());
            agencia_tela.setNome(jTextField2.getText());
            agencia_tela.setEndereco(jTextField3.getText());
            agencia_tela.setNumero(jTextField4.getText());
            agencia_tela.setComplemento(jTextField5.getText());
            agencia_tela.setBairro(jTextField6.getText());
            agencia_tela.setCep(jTextField7.getText());
            agencia_tela.setFone(jTextField8.getText());
            agencia_tela.setUF(jTextField9.getText());
            agencia_tela.setCidade(jTextField10.getText());
            
            objcon.alteraRegistroJFBD("AGENCIAS", agencia_tela.alteraDadosSQLValues(),
            "NUM_AGE = '" + jTextField1.getText()+"'");
            
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");   
        }
        
        operacao = "Alterar";
        if(operacaoAtivaGlobal.equals(operacao)){
            
            ConnectDAO objcon = new ConnectDAO();
            agencia_tela = objcon.pesquisaAgenciaJFBD("AGENCIAS", "NUM_AGE = '" + jTextField1.getText()+"'");
            
            jTextField1.setText(agencia_tela.getNumAgencia());
            jTextField3.setText(agencia_tela.getEndereco());
            jTextField2.setText(agencia_tela.getNome());
            jTextField4.setText(agencia_tela.getNumero());
            jTextField5.setText(agencia_tela.getComplemento());
            jTextField6.setText(agencia_tela.getBairro());
            jTextField7.setText(agencia_tela.getCep());
            jTextField8.setText(agencia_tela.getFone());
            jTextField9.setText(agencia_tela.getUF());
            jTextField10.setText(agencia_tela.getCidade());
            
          jLabel1.setVisible(true);
          jLabel2.setVisible(true);
          jLabel3.setVisible(true);
          jLabel4.setVisible(true);
          jLabel5.setVisible(true);
          jLabel6.setVisible(true);
          jLabel7.setVisible(true);
          jLabel8.setVisible(true);
          jTextField1.setVisible(true);
          jTextField2.setVisible(true);
          jTextField3.setVisible(true);
          jTextField4.setVisible(true);
          jTextField5.setVisible(true);
          jTextField6.setVisible(true);
          jTextField7.setVisible(true);
          jLabel10.setVisible(true);
          jLabel9.setVisible(true);
          jLabel11.setVisible(true);
          jTextField8.setVisible(true);
          jTextField9.setVisible(true);
          jTextField10.setVisible(true);
          
          jButton1.setText("Alterar");
          operacaoAtivaGlobal = "Alteração";
        }
        
        operacao = "Exclusão";
        if (operacaoAtivaGlobal.equals(operacao)){
            
            ConnectDAO objcon = new ConnectDAO();
            objcon.excluiRegistroJFBD("AGENCIAS","NUM_AGE="+jTextField1.getText());
            
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            this.dispose();
        }
        
        operacao = "Excluir";
        if(operacaoAtivaGlobal.equals(operacao)){
            
            ConnectDAO objcon = new ConnectDAO();
            agencia_tela = objcon.pesquisaAgenciaJFBD("AGENCIAS", "NUM_AGE = '" + jTextField1.getText()+"'");
            
            jTextField1.setText(agencia_tela.getNumAgencia());
            jTextField3.setText(agencia_tela.getEndereco());
            jTextField2.setText(agencia_tela.getNome());
            jTextField4.setText(agencia_tela.getNumero());
            jTextField5.setText(agencia_tela.getComplemento());
            jTextField6.setText(agencia_tela.getBairro());
            jTextField7.setText(agencia_tela.getCep());
            jTextField8.setText(agencia_tela.getFone());
            jTextField9.setText(agencia_tela.getUF());
            jTextField10.setText(agencia_tela.getCidade());
            
          jLabel1.setVisible(true);
          jLabel2.setVisible(true);
          jLabel3.setVisible(true);
          jLabel4.setVisible(true);
          jLabel5.setVisible(true);
          jLabel6.setVisible(true);
          jLabel7.setVisible(true);
          jLabel8.setVisible(true);
          jTextField1.setVisible(true);
          jTextField2.setVisible(true);
          jTextField3.setVisible(true);
          jTextField4.setVisible(true);
          jTextField5.setVisible(true);
          jTextField6.setVisible(true);
          jTextField7.setVisible(true);
          jLabel10.setVisible(true);
          jLabel9.setVisible(true);
          jLabel11.setVisible(true);
          jTextField8.setVisible(true);
          jTextField9.setVisible(true);
          jTextField10.setVisible(true);
          
          jTextField1.setEditable(false);
          jTextField2.setEditable(false);
          jTextField3.setEditable(false);
          jTextField4.setEditable(false);
          jTextField5.setEditable(false);
          jTextField6.setEditable(false);
          jTextField7.setEditable(false);
          jTextField8.setEditable(false);
          jTextField9.setEditable(false);
          jTextField10.setEditable(false);
          
          jButton1.setText("Excluir");
          operacaoAtivaGlobal = "Exclusão";
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(agencia_tela.getNumAgencia());
        jTextField2.setText(agencia_tela.getNome());
        jTextField3.setText(agencia_tela.getEndereco());
        jTextField4.setText(agencia_tela.getNumero());
        jTextField5.setText(agencia_tela.getComplemento());
        jTextField6.setText(agencia_tela.getBairro());
        jTextField7.setText(agencia_tela.getCep());
        jTextField8.setText(agencia_tela.getFone());
        jTextField9.setText(agencia_tela.getUF());
        jTextField10.setText(agencia_tela.getCidade());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agências.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agências.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agências.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agências.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agências().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
