/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;
import DAO.ContaCorrente;
import DAO.ConnectDAO;
/**
 *
 * @author Alunos
 */
public class Cad_ContaCorrente extends javax.swing.JFrame {
    String operacaoAtivaGlobal = "Nenhum";
    /**
     * Creates new form Cad_ContaCorrente
     */
    public Cad_ContaCorrente() {
        initComponents();
    }
    public Cad_ContaCorrente (String operacaoAtiva) {
         //construtor
        initComponents ();
        operacaoAtivaGlobal = operacaoAtiva;
        String operacao = "Incluir";
        
        if (operacaoAtiva.equals(operacao)) {
          jButton1.setText("Incluir BD");
          jButton2.setVisible(false);
          jButton3.setVisible(false);
          
          jLabel1.setVisible(true);
          jLabel2.setVisible(true);
          jLabel4.setVisible(true);
          jLabel5.setVisible(true);
          jTextField1.setVisible(true);
          jTextField2.setVisible(true);
          jTextField3.setVisible(true);
          jTextField4.setVisible(true);
        }
        operacao = "Alterar";
        if (operacaoAtiva.equals(operacao)){
          jLabel1.setVisible(false);
          jLabel2.setVisible(false);
          jLabel4.setVisible(false);
          jLabel5.setVisible(false);
          
          jTextField1.setVisible(false);
          jTextField2.setVisible(true);
          jTextField3.setVisible(false);
          jTextField4.setVisible(false);
          
          jButton1.setText("Pesquisar");
          jButton2.setVisible(false);
          jButton3.setVisible(false);
        }
        
        operacao = "Excluir";
        if (operacaoAtiva.equals(operacao)){
          jLabel1.setVisible(false);
          jLabel2.setVisible(true);
          jLabel3.setVisible(false);
          jLabel4.setVisible(false);
          jLabel5.setVisible(false);
          jLabel6.setVisible(false);
          jTextField1.setVisible(false);
          jTextField2.setVisible(true);
          jTextField3.setVisible(false);
          jTextField4.setVisible(false);
          
          jButton1.setVisible(false);
          jButton2.setVisible(false);
          jButton3.setText("Pesquisar-Excluir");
        }
    }
    ContaCorrente cad_contaCorrente = new ContaCorrente();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número da agência:");

        jLabel2.setText("Número da Conta Corrente:");

        jLabel4.setText("Id do Cliente:");

        jLabel5.setText("Saldo:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Confirmar cadastro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Consulta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel6.setText("Cadastro Conta Corrente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField2))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        if (operacaoAtivaGlobal.equals(operacao))
        {
        cad_contaCorrente.setNumAge(Integer.parseInt(jTextField1.getText()));
        cad_contaCorrente.setNumCc(Integer.parseInt(jTextField2.getText()));
        cad_contaCorrente.setIdCli(Integer.parseInt(jTextField3.getText()));
        cad_contaCorrente.setSaldo(Integer.parseInt(jTextField4.getText()));
        
        ConnectDAO objcon = new ConnectDAO();
            objcon.connectDB();
            objcon.insereRegistroJFBD("CONTACORRENTE", cad_contaCorrente.dadosSQLValues());
            
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        }
        
        operacao = "Alteração";
        if (operacaoAtivaGlobal.equals(operacao)){
            
            ConnectDAO objcon = new ConnectDAO();
            
            ContaCorrente cad_contaCorrente = new ContaCorrente();
            cad_contaCorrente.setNumAge(Integer.parseInt(jTextField1.getText()));
            cad_contaCorrente.setNumCc(Integer.parseInt(jTextField2.getText()));
            cad_contaCorrente.setIdCli(Integer.parseInt(jTextField3.getText()));
            cad_contaCorrente.setSaldo(Integer.parseInt(jTextField4.getText()));
            
            objcon.alteraRegistroJFBD("CONTACORRENTE", cad_contaCorrente.alteraDadosSQLValues(),
            "NUM_CC = '" + jTextField1.getText()+"'");
            
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
        }
        
        operacao = "Alterar";
        if(operacaoAtivaGlobal.equals(operacao)){
            
            ConnectDAO objcon = new ConnectDAO();
      
            cad_contaCorrente = objcon.pesquisaContaCorrenteJFBD("CONTACORRENTE", "NUM_CC = '" + jTextField2.getText()+"'");
            
            jTextField1.setText(Integer.toString(cad_contaCorrente.getNumAge()));
            jTextField2.setText(Long.toString(cad_contaCorrente.getNumCc()));
            jTextField3.setText(Integer.toString(cad_contaCorrente.getIdCli()));
            jTextField4.setText(Integer.toString(cad_contaCorrente.getSaldo()));
            
          jLabel1.setVisible(true);
          jLabel2.setVisible(true);
          jLabel4.setVisible(true);
          jLabel5.setVisible(true);
          jTextField1.setVisible(true);
          jTextField2.setVisible(true);
          jTextField3.setVisible(true);
          jTextField4.setVisible(true);
          
          jButton1.setText("Alterar");
          operacaoAtivaGlobal = "Alteração";
        }
        
        operacao = "Exclusão";
        if (operacaoAtivaGlobal.equals(operacao)){
            
            ConnectDAO objcon = new ConnectDAO();
            objcon.excluiRegistroJFBD("CONTACORRENTE","NUM_CC="+jTextField2.getText());
            
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            this.dispose();
        }
        
        operacao = "Excluir";
        if(operacaoAtivaGlobal.equals(operacao)){
            
            ConnectDAO objcon = new ConnectDAO();
            cad_contaCorrente = objcon.pesquisaContaCorrenteJFBD("CONTACORRENTE", "NUM_CC = '" + jTextField2.getText()+"'");
            
            jTextField1.setText(Integer.toString(cad_contaCorrente.getNumAge()));
            jTextField3.setText(Long.toString(cad_contaCorrente.getNumCc()));
            jTextField2.setText(Integer.toString(cad_contaCorrente.getIdCli()));
            jTextField4.setText(Integer.toString(cad_contaCorrente.getSaldo()));
           
          jLabel1.setVisible(true);
          jLabel2.setVisible(true);
          jLabel3.setVisible(true);
          jLabel4.setVisible(true);
          jLabel5.setVisible(true);
          jLabel6.setVisible(true);
          jTextField1.setVisible(true);
          jTextField2.setVisible(true);
          jTextField3.setVisible(true);
          jTextField4.setVisible(true);
          
          jTextField1.setEditable(false);
          jTextField2.setEditable(false);
          jTextField3.setEditable(false);
          jTextField4.setEditable(false);
          
          jButton3.setText("Excluir");
          operacaoAtivaGlobal = "Exclusão";
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(String.valueOf(cad_contaCorrente.getNumAge()));
        jTextField2.setText(String.valueOf(cad_contaCorrente.getNumCc()));
        jTextField3.setText(String.valueOf(cad_contaCorrente.getIdCli()));
        jTextField4.setText(String.valueOf(cad_contaCorrente.getSaldo()));
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_ContaCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_ContaCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_ContaCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_ContaCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Cad_ContaCorrente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
