/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import DAO.Clientes;
import DAO.Historico;
import DAO.ConnectDAO;
import java.util.Set;
/**
 *
 * @author Alunos
 */
public class Historicos extends javax.swing.JFrame {
    String operacaoAtivaGlobal = "Nenhum";
    /**
     * Creates new form Histórico
     */
    public Historicos() {
        initComponents();
    }
    public Historicos (String operacaoAtiva) {
        //construtor
        initComponents ();
        operacaoAtivaGlobal = operacaoAtiva;
        String operacao = "Incluir";
        
        if (operacaoAtiva.equals(operacao)) {
          jButton1.setVisible(false);
          jButton2.setVisible(false);
          jButton3.setText("Incluir BD");
          
          jLabel1.setVisible(true);
          jLabel2.setVisible(true);
          jTextField1.setVisible(true);
          jTextField2.setVisible(true);
        }
        
         operacao = "Alterar";
        if (operacaoAtiva.equals(operacao)){
          jLabel2.setVisible(false);
          jLabel3.setVisible(false);
          jTextField1.setVisible(true);
          jTextField2.setVisible(false);
          
          jButton1.setVisible(false);
          jButton2.setVisible(false);
          jButton3.setText("Pesquisar");
        }
        
        operacao = "Excluir";
        if (operacaoAtiva.equals(operacao)){
         
          jLabel2.setVisible(false);
          jLabel3.setVisible(false);
          jTextField1.setVisible(true);
          jTextField2.setVisible(false);
          
          jButton1.setVisible(false);
          jButton2.setVisible(false);
          jButton3.setText("Pesquisar-Excluir");
        }
}
    Historico tela_his = new Historico();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id_Historico:");

        jLabel2.setText("Descrição:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar tela");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Histórico");

        jButton3.setText("Cadastrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(jTextField2))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        //jTextField1.setText(tela_his.getIdHis());
        //jTextField2.setText(tela_his.getDescricao());
        String operacao = "Incluir";
        if (operacaoAtivaGlobal.equals(operacao))
        {
        tela_his.setIdHis(jTextField1.getText());
        tela_his.setDescricao(jTextField2.getText());
        
        ConnectDAO objcon = new ConnectDAO();
            objcon.connectDB();
            objcon.insereRegistroJFBD("HISTORICOS", tela_his.dadosSQLValues());
            
        jTextField1.setText("");
        jTextField2.setText("");
        }
        
        operacao = "Alteração";
        if (operacaoAtivaGlobal.equals(operacao)){
            
            ConnectDAO objcon = new ConnectDAO();
            
            Historico tela_his = new Historico();
            tela_his.setIdHis(jTextField1.getText());
            tela_his.setDescricao(jTextField2.getText());
            
            objcon.alteraRegistroJFBD("HISTORICOS", tela_his.alteraDadosSQLValues(),
            "ID_HIS = '" + jTextField1.getText()+"'");
            
            jTextField1.setText("");
            jTextField2.setText("");   
        }
        
        operacao = "Alterar";
        if(operacaoAtivaGlobal.equals(operacao)){
            
            ConnectDAO objcon = new ConnectDAO();
            tela_his = objcon.pesquisaHistoricoJFBD("HISTORICOS", "ID_HIS = '" + jTextField1.getText()+"'");
            
            jTextField1.setText(tela_his.getIdHis());
            jTextField2.setText(tela_his.getDescricao());
            
            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
          
            jButton3.setText("Alterar");
            operacaoAtivaGlobal = "Alteração";
        }
        
        operacao = "Exclusão";
        if (operacaoAtivaGlobal.equals(operacao)){
            
            ConnectDAO objcon = new ConnectDAO();
            objcon.excluiRegistroJFBD("HISTORICOS","ID_HIS="+jTextField1.getText());
            
            jTextField1.setText("");
            jTextField2.setText("");
            this.dispose();
        }
        
        operacao = "Excluir";
        if(operacaoAtivaGlobal.equals(operacao)){
            
            ConnectDAO objcon = new ConnectDAO();
            tela_his = objcon.pesquisaHistoricoJFBD("HISTORICOS", "ID_HIS = '" + jTextField1.getText()+"'");
            
            jTextField1.setText(tela_his.getIdHis());
            jTextField2.setText(tela_his.getDescricao());
            
            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
          
            jTextField1.setEditable(false);
            jTextField2.setEditable(false);
          
            jButton3.setText("Excluir");
            operacaoAtivaGlobal = "Exclusão";
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Historicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

  
}
