/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;
import DAO.Clientes;
import DAO.Usuarios;
import DAO.ConnectDAO;
/**
 *
 * @author Alunos
 */
public class Usuários extends javax.swing.JFrame {
    String operacaoAtivaGlobal = "Nenhum";
    /**
     * Creates new form Usuários
     */
    public Usuários() {
        initComponents();
    }
    public Usuários (String operacaoAtiva) {
        initComponents ();
        operacaoAtivaGlobal = operacaoAtiva;
        String operacao = "Incluir";
        
        if (operacaoAtiva.equals(operacao)) {
          jButton1.setText("Incluir BD");
          jButton2.setVisible(false);
          jButton3.setVisible(false);
          
          jLabel1.setVisible(true);
          jLabel2.setVisible(true);
          jLabel3.setVisible(true);
          jLabel4.setVisible(true);
          jTextField1.setVisible(true);
          jTextField2.setVisible(true);
          jTextField3.setVisible(true);
          jTextField4.setVisible(true);
        }
        
        operacao = "Alterar";
        if (operacaoAtiva.equals(operacao)){
          jLabel1.setVisible(true);
          jLabel2.setVisible(false);
          jLabel3.setVisible(false);
          jLabel4.setVisible(false);
          jLabel5.setVisible(false);
          
          jTextField1.setVisible(true);
          jTextField2.setVisible(false);
          jTextField3.setVisible(false);
          jTextField4.setVisible(false);
          
          jButton1.setText("Pesquisar");
          jButton2.setVisible(false);
          jButton3.setVisible(false);
        }
        
        operacao = "Excluir";
        if (operacaoAtiva.equals(operacao)){
          jLabel1.setVisible(true);
          jLabel2.setVisible(false);
          jLabel3.setVisible(false);
          jLabel4.setVisible(false);
          jLabel5.setVisible(false);
          jTextField1.setVisible(true);
          jTextField2.setVisible(false);
          jTextField3.setVisible(false);
          jTextField4.setVisible(false);
          
          
          jButton1.setText("Pesquisar-Excluir");
          jButton2.setVisible(false);
          jButton3.setVisible(false);
        }
    }
    
    Usuarios usuario_tela = new Usuarios(); 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id Usuário: ");

        jLabel2.setText("Senha: ");

        jLabel3.setText("Número da Agência: ");

        jLabel4.setText("Numero CC:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Usuários");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpar Tela");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2)
                        .addGap(34, 34, 34)
                        .addComponent(jButton3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        if (operacaoAtivaGlobal.equals(operacao))
        {
        usuario_tela.setId(jTextField1.getText());
        usuario_tela.setSenha(jTextField2.getText());
        usuario_tela.setNumAge(Integer.parseInt(jTextField3.getText()));
        usuario_tela.setNumCc(Integer.parseInt(jTextField4.getText()));
        
        ConnectDAO objcon = new ConnectDAO();
            objcon.connectDB();
            objcon.insereRegistroJFBD("USUARIOS", usuario_tela.dadosSQLValues());
            
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        }
        
        operacao = "Alteração";
        if (operacaoAtivaGlobal.equals(operacao)){
            
            ConnectDAO objcon = new ConnectDAO();
            
            Usuarios usuario_tela = new Usuarios();
            usuario_tela.setId(jTextField1.getText());
            usuario_tela.setSenha(jTextField3.getText());
            usuario_tela.setNumAge(Integer.parseInt(jTextField3.getText()));
            usuario_tela.setNumCc(Integer.parseInt(jTextField4.getText()));
            
            objcon.alteraRegistroJFBD("USUARIOS", usuario_tela.alteraDadosSQLValues(),
            "ID = '" + jTextField1.getText()+"'");
            
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
        }
        
        operacao = "Alterar";
        if(operacaoAtivaGlobal.equals(operacao)){
            
            ConnectDAO objcon = new ConnectDAO();
            usuario_tela = objcon.pesquisaUsuarioJFBD("USUARIOS", "ID = '" + jTextField1.getText()+"'");
            
            jTextField1.setText(usuario_tela.getId());
            jTextField3.setText(usuario_tela.getSenha());
            jTextField2.setText(Integer.toString(usuario_tela.getNumAge()));
            jTextField4.setText(Long.toString(usuario_tela.getNumCc()));
            
          jLabel1.setVisible(true);
          jLabel2.setVisible(true);
          jLabel3.setVisible(true);
          jLabel4.setVisible(true);
          jTextField1.setVisible(true);
          jTextField2.setVisible(true);
          jTextField3.setVisible(true);
          jTextField4.setVisible(true);
         
          jButton1.setText("Alterar");
          operacaoAtivaGlobal = "Alteração";
        }
        
        operacao = "Exclusão";
        if (operacaoAtivaGlobal.equals(operacao)){
            
            ConnectDAO objcon = new ConnectDAO();
            objcon.excluiRegistroJFBD("USUARIOS","ID="+jTextField1.getText());
            
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            this.dispose();
        }
        
        operacao = "Excluir";
        if(operacaoAtivaGlobal.equals(operacao)){
            
            ConnectDAO objcon = new ConnectDAO();
            usuario_tela = objcon.pesquisaUsuarioJFBD("USUARIOS", "ID = '" + jTextField1.getText()+"'");
            
            jTextField1.setText(usuario_tela.getId());
            jTextField3.setText(usuario_tela.getSenha());
            jTextField2.setText(Integer.toString(usuario_tela.getNumAge()));
            jTextField4.setText(Long.toString(usuario_tela.getNumCc()));
            
          jLabel1.setVisible(true);
          jLabel2.setVisible(true);
          jLabel3.setVisible(true);
          jLabel4.setVisible(true);
          jLabel5.setVisible(true);
          jTextField1.setVisible(true);
          jTextField2.setVisible(true);
          jTextField3.setVisible(true);
          jTextField4.setVisible(true);
          
          jTextField1.setEditable(false);
          jTextField2.setEditable(false);
          jTextField3.setEditable(false);
          jTextField4.setEditable(false);
          
          jButton1.setText("Excluir");
          operacaoAtivaGlobal = "Exclusão";
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(usuario_tela.getId());
        jTextField2.setText(usuario_tela.getSenha());
        jTextField3.setText(String.valueOf(usuario_tela.getNumAge()));
        jTextField4.setText(String.valueOf(usuario_tela.getNumCc()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Usuários().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
